### ISSUE TITLE
How to view study plans?

### ISSUE THREAD

**Issue by ArtistYay** [jassics/security-study-plan#16]
Hello Jassics, I'm interested in the Azure Security study guide but when I open the .md file I don't see anything. Am I missing something? I've also Git-cloned the repo. Here's a screenshot of what I see: 
![2023-05-04 11_10_53-security-study-plan_azure-security-study-plan md at main · jassics_security-stud](https://user-images.githubusercontent.com/72479678/236251167-50a2d0c4-45a2-48a0-9ba6-dad81ec308a4.png)

**Comment by jassics** [comment]
Thank you for raising an issue @ArtistYay 
I am working on it. It will be updated in 2-3 weeks.
